### ISSUE TITLE
1920 x 1080 resolution adaptation

### ISSUE THREAD

**Issue by mehdiselbi** [deepsidh9/Live-Valorant-Overlay#1]
Hi there, 
cool app thanks for the contribution and effort, how can we make it work with 1920 x 1080 resolution since its the most common one and the ocr fails to detect scores and weapons / shields and ult points when the resolution is not 1920 x 1200

Thanks

**Comment by deepsidh9** [comment]
Hey!
Thank you! To make it work with 1920 x 1080 resolution , you'd have to firstly change the hard-coded coordinates of various information points such as the scoreboard agent, weapon, ultimate number icon positions and secondly scale down the template for the required entities. For example you'd have to scale the agent icons under Original Agent Icons directory differently for 1920x1080 as they are rendered differently because of the different resolution. Once you have written the scaling logic you can make it work for any resolution. Or take a different, long way which is : generate templates for 1920x1080 if you wish to make it work for ONLY that resolution.

**Comment by mehdiselbi** [comment]
been working on this lately no results , for example i tried to adjust the score positions and get the frames in 1920x 1080 but no results so far :/ 
also how can we add chamber

**Comment by deepsidh9** [comment]
The score functionality is currently disabled, its better to get the score from the in-game API. If you would still like to get the score through OCR, then set width and height in get_live_frames.py, make changes to the coordinates accordingly in score.py and uncomment the score module usage in live_details.py. 

To add Chamber, add the name with his required number of ultimate points to  agents_ultimate_points in constants.py and his icon in all the relevant places.

**Comment by mehdiselbi** [comment]
Thanks for the help, its working, chamber added and I'm getting scores too using OCR in-game API I dunno how it works,
I'm still working on the templates for 1920x1080 I generated my own ones and updates the coordinations but I'm still not able to get shields ult points and weapons, I'm missing something trying to figure it out !!

**Comment by deepsidh9** [comment]
Hey, I've made a new [branch ](https://github.com/deepsidh9/Live-Valorant-Overlay/tree/1920x1080 ) which supports the 1920x1080 resolution and has some more completed functionalities. Let me know if you'd like me to share additional information on how I did the changes.
