### ISSUE TITLE
Resolution Change

### ISSUE THREAD

**Issue by LPBlive** [deepsidh9/Live-Valorant-Overlay#3]
Maybe make a config json to configure the personal Resolution. That will be help. I am to dumb to change that in the code so.... xD

btw very nice project :3 

edit: I saw the closed issue "1920x1080"

Which coordinates have i to change? Every coordinate with the comment fix this or also others?

**Comment by LPBlive** [comment]
Sorry... misclick

**Comment by deepsidh9** [comment]
Hey! You'd have to change the coordinates for each entity such as the weapon loadout starting coordinates, the agent icon coordinates; basically change  the coordinates for each *desired* entity. Now you'd have to correlate the new coordinates with the scaled down/newly generated templates for each entity.

**Comment by deepsidh9** [comment]
Hey, I've made a new [branch](https://github.com/deepsidh9/Live-Valorant-Overlay/tree/1920x1080) which **supports the 1920x1080 resolution** and has some more completed functionalities. You can inspect that branch and see the changes that I did. It will help you to understand what is needed to be done in order to make it work for a different resolution.
